{{- if .Values.receiver.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}-receiver-hashring
data:
  hashrings.json: |
    [
      {
        "endpoints": [
          {{- range $i, $e := until (int .Values.receiver.replicaCount) }}
            "{{ include "prometheus-thanos.fullname" $ }}-receiver-{{ $i }}.{{ include "prometheus-thanos.fullname" $ }}-receiver.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.service.receiver.grpc.port }}"

            {{- if lt $i (sub (int $.Values.receiver.replicaCount) 1) -}}
            ,
            {{- end -}}
          {{- end }}
        ]
      }
    ]
{{- end }}
